// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPSo9u6oO0dZqPuVJGq8B9yfmvH2JG_L4',
    appId: '1:487293769029:web:9e7bb518913403094dda2c',
    messagingSenderId: '487293769029',
    projectId: 'netflix-1dc9e',
    authDomain: 'netflix-1dc9e.firebaseapp.com',
    storageBucket: 'netflix-1dc9e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBavO90X2FgIPdoAN9FXbrMb-X06AOl9B4',
    appId: '1:487293769029:android:9e691e0922cb97d54dda2c',
    messagingSenderId: '487293769029',
    projectId: 'netflix-1dc9e',
    storageBucket: 'netflix-1dc9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKV_sXPK3D5HUvZPwQcKV6KA7ulIcVh3E',
    appId: '1:487293769029:ios:7d8bdc2f2f06c1f14dda2c',
    messagingSenderId: '487293769029',
    projectId: 'netflix-1dc9e',
    storageBucket: 'netflix-1dc9e.appspot.com',
    iosBundleId: 'com.example.netflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKV_sXPK3D5HUvZPwQcKV6KA7ulIcVh3E',
    appId: '1:487293769029:ios:a206e2b454e1fa2b4dda2c',
    messagingSenderId: '487293769029',
    projectId: 'netflix-1dc9e',
    storageBucket: 'netflix-1dc9e.appspot.com',
    iosBundleId: 'com.example.netflix.RunnerTests',
  );
}
